Parameters:
  FunctionName:
    Type: String
  ApiId:
    Type: String
  RouteKey:
    Type: String

Resources:
  Integration:
    Type: 'AWS::ApiGatewayV2::Integration'
    Properties:
      ApiId: !Ref ApiId
      IntegrationType: AWS_PROXY
      PayloadFormatVersion: 1.0
      IntegrationUri: !Sub  "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:eu-west-1:${AWS::AccountId}:function:${FunctionName}/invocations"
  Route:
    Type: 'AWS::ApiGatewayV2::Route'
    DependsOn:
      - Integration
    Properties:
      ApiId: !Ref ApiId
      RouteKey: !Ref RouteKey
      AuthorizationType: NONE
      Target: !Join
        - /
        - - integrations
          - !Ref Integration
  LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Sub arn:aws:lambda:eu-west-1:${AWS::AccountId}:function:${FunctionName}
      Principal: apigateway.amazonaws.com
      SourceArn: !Join
        - ''
        - - 'arn:aws:execute-api:'
          - !Ref AWS::Region
          - ":"
          - !Ref AWS::AccountId
          - !Sub ":${ApiId}/*/*"
